### ISSUE TITLE
Issue on iPad

### ISSUE THREAD

**Issue by bouziane** [eyev-de/skyle_ik#1]
I’m encountering an error when trying to run the Skyle IK app on an iPad. 
The error message is as follows:

> [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method ensureInitialized on channel window_manager)
> #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
> <asynchronous suspension>
> #1      WindowManager.ensureInitialized (package:window_manager/src/window_manager.dart:104:5)
> <asynchronous suspension>
> #2      main (package:skyle_ik/main.dart:26:3)
> <asynchronous suspension>

**Comment by krjw-eyev** [comment]
I have pushed a fix for that. [You can download 2.2.0 again here](https://github.com/eyev-de/skyle_ik/releases/tag/2.2.0)
